# docker-compose.yml
version: '3.8'

services:
  token-calculator:
    build: .
    container_name: token-calculator
    restart: always
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-default-secret-key}
    volumes:
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 --timeout 120 "app:create_app()"
